print('Hello World')
print('Hello Shogun')
print('Hello World')
print('Hello Shogun')
print('Hello World')
print('Hello Shogun')
print('Hello World')
print('Hello Shogun')
print('Hello World')
print('Hello Shogun')
print('Hello World')
print('Hello Shogun')
print('Hello World')
print('Hello Shogun')
print('Hello World')
print('Hello Shogun')
print('Hello World')
print('Hello Shogun')


friend = ['loong','Pa lek','Loong Dam']
print(friend[0])
